# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rammc\Documents\Pycharm3\BDO_Enhancement_Tool\Forms\dlgCompact.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgCompact(object):
    def setupUi(self, dlgCompact):
        dlgCompact.setObjectName("dlgCompact")
        dlgCompact.resize(465, 116)
        self.gridLayout = QtWidgets.QGridLayout(dlgCompact)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(dlgCompact)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmdDownagrade = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdDownagrade.sizePolicy().hasHeightForWidth())
        self.cmdDownagrade.setSizePolicy(sizePolicy)
        self.cmdDownagrade.setMinimumSize(QtCore.QSize(25, 0))
        self.cmdDownagrade.setObjectName("cmdDownagrade")
        self.verticalLayout.addWidget(self.cmdDownagrade)
        self.gridLayout.addWidget(self.widget, 0, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(dlgCompact)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cmdUpgrade = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdUpgrade.sizePolicy().hasHeightForWidth())
        self.cmdUpgrade.setSizePolicy(sizePolicy)
        self.cmdUpgrade.setMinimumSize(QtCore.QSize(25, 0))
        self.cmdUpgrade.setObjectName("cmdUpgrade")
        self.verticalLayout_2.addWidget(self.cmdUpgrade)
        self.gridLayout.addWidget(self.widget_2, 0, 5, 1, 1)
        self.widget_3 = QtWidgets.QWidget(dlgCompact)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblInfo = QtWidgets.QLabel(self.widget_3)
        self.lblInfo.setText("")
        self.lblInfo.setObjectName("lblInfo")
        self.verticalLayout_3.addWidget(self.lblInfo)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmdSuccess = QtWidgets.QPushButton(self.widget_4)
        self.cmdSuccess.setStyleSheet("QPushButton{\n"
"background:green;\n"
"}")
        self.cmdSuccess.setObjectName("cmdSuccess")
        self.horizontalLayout.addWidget(self.cmdSuccess)
        self.cmdFail = QtWidgets.QPushButton(self.widget_4)
        self.cmdFail.setStyleSheet("QPushButton{\n"
"background:red;\n"
"}")
        self.cmdFail.setObjectName("cmdFail")
        self.horizontalLayout.addWidget(self.cmdFail)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.gridLayout.addWidget(self.widget_3, 0, 6, 1, 1)
        self.cmdChoices = QtWidgets.QPushButton(dlgCompact)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdChoices.sizePolicy().hasHeightForWidth())
        self.cmdChoices.setSizePolicy(sizePolicy)
        self.cmdChoices.setMinimumSize(QtCore.QSize(0, 20))
        self.cmdChoices.setObjectName("cmdChoices")
        self.gridLayout.addWidget(self.cmdChoices, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(dlgCompact)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinFS = QtWidgets.QSpinBox(dlgCompact)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.spinFS.setFont(font)
        self.spinFS.setMaximum(999)
        self.spinFS.setObjectName("spinFS")
        self.gridLayout.addWidget(self.spinFS, 0, 1, 1, 1)
        self.cmdFsShelf = QtWidgets.QPushButton(dlgCompact)
        self.cmdFsShelf.setObjectName("cmdFsShelf")
        self.gridLayout.addWidget(self.cmdFsShelf, 1, 1, 1, 1)
        self.cmdDigestShelf = QtWidgets.QPushButton(dlgCompact)
        self.cmdDigestShelf.setObjectName("cmdDigestShelf")
        self.gridLayout.addWidget(self.cmdDigestShelf, 1, 6, 1, 1)
        self.widget_5 = QtWidgets.QWidget(dlgCompact)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblGearPicture = QtWidgets.QLabel(self.widget_6)
        self.lblGearPicture.setMinimumSize(QtCore.QSize(32, 32))
        self.lblGearPicture.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblGearPicture.setText("")
        self.lblGearPicture.setObjectName("lblGearPicture")
        self.verticalLayout_4.addWidget(self.lblGearPicture)
        self.lblGear = QtWidgets.QLabel(self.widget_6)
        self.lblGear.setMinimumSize(QtCore.QSize(0, 0))
        self.lblGear.setStyleSheet("")
        self.lblGear.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblGear.setWordWrap(True)
        self.lblGear.setObjectName("lblGear")
        self.verticalLayout_4.addWidget(self.lblGear)
        self.horizontalLayout_2.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblGearPicture_2 = QtWidgets.QLabel(self.widget_7)
        self.lblGearPicture_2.setMinimumSize(QtCore.QSize(32, 32))
        self.lblGearPicture_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblGearPicture_2.setText("")
        self.lblGearPicture_2.setObjectName("lblGearPicture_2")
        self.verticalLayout_5.addWidget(self.lblGearPicture_2)
        self.lblGear_2 = QtWidgets.QLabel(self.widget_7)
        self.lblGear_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lblGear_2.setStyleSheet("")
        self.lblGear_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblGear_2.setWordWrap(True)
        self.lblGear_2.setObjectName("lblGear_2")
        self.verticalLayout_5.addWidget(self.lblGear_2)
        self.horizontalLayout_2.addWidget(self.widget_7)
        self.gridLayout.addWidget(self.widget_5, 0, 3, 1, 2)

        self.retranslateUi(dlgCompact)
        QtCore.QMetaObject.connectSlotsByName(dlgCompact)

    def retranslateUi(self, dlgCompact):
        _translate = QtCore.QCoreApplication.translate
        dlgCompact.setWindowTitle(_translate("dlgCompact", "Graveflo Enhance Calc"))
        self.cmdDownagrade.setToolTip(_translate("dlgCompact", "Downgrade Gear"))
        self.cmdDownagrade.setText(_translate("dlgCompact", "<"))
        self.cmdUpgrade.setToolTip(_translate("dlgCompact", "Upgrade Gear"))
        self.cmdUpgrade.setText(_translate("dlgCompact", ">"))
        self.cmdSuccess.setText(_translate("dlgCompact", "SUCCESS"))
        self.cmdFail.setText(_translate("dlgCompact", "FAIL"))
        self.cmdChoices.setToolTip(_translate("dlgCompact", "Information Shelf"))
        self.cmdChoices.setText(_translate("dlgCompact", "Choices"))
        self.label.setText(_translate("dlgCompact", "FS:"))
        self.spinFS.setToolTip(_translate("dlgCompact", "Current Failstack Value"))
        self.cmdFsShelf.setText(_translate("dlgCompact", "Fail Stacks"))
        self.cmdDigestShelf.setText(_translate("dlgCompact", "Digest"))
        self.lblGear.setToolTip(_translate("dlgCompact", "Selected Gear"))
        self.lblGear.setText(_translate("dlgCompact", "Gear"))
        self.lblGear_2.setToolTip(_translate("dlgCompact", "Selected Gear"))
        self.lblGear_2.setText(_translate("dlgCompact", "Gear"))

